### ISSUE TITLE
Где хранить компоненты и модули?

### ISSUE THREAD

**Issue by turingal** [mepihindeveloper/yawas#1]
Если есть общие компоненты, например, компонент для построения структуры дерева (массивы/объекты), то где хранить их?

**Comment by maksimepikhin** [comment]
Хороший вопрос по данной структуре. Хранить это дело вне `src` крайне не логично, так как эти вещи будут иметь прямое отношение к приложению. Хранить прямо в `src` - мешанина папок. Скорее всего, будет лучшим решением применить вот [эту структуру](https://github.com/mepihindeveloper/yawas/issues/2#issuecomment-1097925015), а тогда и в корень `src` все ляжет грамотно. По "внутренностям" папок компонентов и модулей уже на ваше усмотрение. Тут можно и разбить внутри на "подсистемы", а можно хранить и так.

Ответил на вопрос?

**Comment by turingal** [comment]
Да, спасибо. Понятно.
