### ISSUE TITLE
Как быть с модульностью, если надо разделить приложение на 2 составных?

### ISSUE THREAD

**Issue by i-programmer** [mepihindeveloper/yawas#2]
Если надо разделить приложение на 2 составных, например для клиента интернет-магазина и панели админа, то как в такой структуре это сделать грамотно?

**Comment by maksimepikhin** [comment]
Здесь может быть несколько вариантов:

1. Добавлять вложенные папки в структуру, чтобы получать примерно так: `src/presentation/controllers/admin`
2. Разбить все "подсистемы" на папки, чтобы в `src` была примерно такая структура: `src/admin-application` и `src/client-application`. В таком случае, каждая папка (`*-application`) должна повторить текущую структуру папки `src`. Это дополнительно позволит добавить "глобальный" класс управления "подсистемой": `src/admin-application/AdminBundle.php`.

Универсального варианта тут не будет, но лично мне ближе второй вариант с четким разделением. Да, будет дублирование структуры, но, если мы рассматриваем это все как "подсистемы", то логично их не связывать с глобальной структурой, создавая под них папку в текущей структуре. Это еще плохо сыграет на "выпиливание" "подсистемы", так как придется удалять вложенные папки во всех папках...

Ответил на вопрос?

**Comment by maksimepikhin** [comment]
Здесь может быть несколько вариантов:

1. Добавлять вложенные папки в структуру, чтобы получать примерно так: `src/presentation/controllers/admin`
2. Разбить все "подсистемы" на папки, чтобы в `src` была примерно такая структура: `src/admin-application` и `src/client-application`. В таком случае, каждая папка (`*-application`) должна повторить текущую структуру папки `src`. Это дополнительно позволит добавить "глобальный" класс управления "подсистемой": `src/admin-application/AdminBundle.php`.

Универсального варианта тут не будет, но лично мне ближе второй вариант с четким разделением. Да, будет дублирование структуры, но, если мы рассматриваем это все как "подсистемы", то логично их не связывать с глобальной структурой, создавая под них папку в текущей структуре. Это еще плохо сыграет на "выпиливание" "подсистемы", так как придется удалять вложенные папки во всех папках...

Ответил на вопрос?

**Comment by i-programmer** [comment]
Да, второй вариант ближе и понятнее. Ясно. Спасибо.
